name: Build and Push to GHCR

on:
  push:
    branches:
      - main  # 触发分支

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. 设置 Node.js 环境
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # 根据你的需求调整版本

    # 3. 安装依赖
    - name: Install dependencies
      run: npm install



    # 5. 构建 Docker 镜像
    - name: Build Docker image
      run: |
        docker build -t node-argo:latest .

    # 6. 登录 Docker Hub
    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin


    # 7. 推送 Docker 镜像
    - name: Push Docker image
      run: |
        docker tag node-argo:latest ahpamer/node-argo:latest

        docker push ahpamer/node-argo:latest



        

